baseURL: https://fngtz.github.io/
languageCode: zh
title: Fngtz's Blog
theme: "PaperMod"
homeInfoParams:
  Title: Welcome to Fngtz's Blog
  Content: "..."
socialIcons:
  - name: "email"
    url: "mailto:fngtz@outlook.com"